source("inst/run-day-01.R", local = TRUE)
source("inst/run-day-02.R", local = TRUE)
source("inst/run-day-03.R", local = TRUE)
source("inst/run-day-04.R", local = TRUE)
source("inst/run-day-05.R", local = TRUE)
source("inst/run-day-06.R", local = TRUE)
source("inst/run-day-07.R", local = TRUE)
source("inst/run-day-08.R", local = TRUE)
